version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file: .dev.env
    environment:
      APP_PORT: int
      BACKEND_PORT: int
    networks:
      - user_eat
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file: .dev.env
    networks:
      - user_eat
    volumes:
      - postgres_db:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    env_file: .dev.env
    networks:
      - user_eat

volumes:
  postgres_db:

networks:
  user_eat:
    driver: bridge
